### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by JimMadge**
Naming @harisood and @manics as contacts on behalf of UK TRE.

### CODE REVIEW

**Comment by manics** [comment]
Is this CoC specific to this repository? Or should I create a new `.github` repo and have a single CoC at the org level that applies to all repos?
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by JimMadge** [comment]
Nothing specific to this repo (in fact I copied it from the website repo).

Having a unified CoC for all repositories makes sense if you are @harisood are happy to play that role.
From the docs I'm assuming that if someone were to clone the repo it wouldn't contain the code of conduct, which feels like a loss but I don't think that is a hill to die on centralising this makes sense.

**Comment by manics** [comment]
I've added a .github https://github.com/uk-tre/.github/blob/main/CODE_OF_CONDUCT.md

You could add a `## Code of conduct` to the README that links to https://github.com/uk-tre/.github/blob/main/CODE_OF_CONDUCT.md ?

**Review by craddm — APPROVED** [review]
LGTM

**Review by manics — COMMENTED** [review]
What do you think of making the code of conduct a level 2 heading to emphasise it applies to everyone and not just "contributors" (for some definition of "contributors")?

**Pull request merged**
